#!/usr/bin/env bash
# Kodhane deletion log (silme listesi): SEPARATE install step for migration 20261003040000. Not part of package B
# (kodhane_v44b_install.sh / install.sql) and not covered by its approval. Runbook: docs/kodhane-account-delete-runbook.md
# "Silme listesi". Steps (one run directory $KODHANE_OUT):
#   build      input md5s (kodhane_deletion_log/inputs.md5), generate the SQL into $KODHANE_OUT/sql (+ sql.md5)
#   preflight  READ ONLY: target (Kodhane, not Fenomen), existing objects
#   dryrun     migration + install check in one transaction, ROLLBACK
#   install    the same with COMMIT (needs PASS of preflight and dryrun in this run directory; live: KODHANE_LIVE_APPROVAL)
#   verify     READ ONLY install check (schema / table owner, RLS, no API role privileges, CHECKs, 45 days, functions)
#   rollback   rollback file (refuses while the list has rows unless KODHANE_ALLOW_DELETION_LOG_LOSS=on; live: approval)
# Target: KODHANE_TARGET=local (KODHANE_CT, KODHANE_DB) | live (PORTAINER_API_TOKEN, pexec), see kodhane_deletion_log/lib.sh.
# No backup step of its own: the migration only adds objects (new schema, table, two functions); take the usual DB backup
# first if one is not recent. After the install: the account delete writes the list; export + retention steps follow.
# Exit 0 = step PASS; 1 = STOP / FAIL; 2 = usage.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; SB="$(cd "$HERE/.." && pwd)"; D="$HERE/kodhane_deletion_log"
. "$D/lib.sh"
MIG=migrations/20261003040000_v4_4_kodhane_deletion_log.sql; RB=rollback/20261003040000_v4_4_kodhane_deletion_log.rollback.sql
STEP="${1:-}"; OUT="${KODHANE_OUT:-}"
[[ -n "$STEP" ]] || { sed -n '2,18p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 2; }
[[ -n "$OUT" ]] || dl_die "KODHANE_OUT (run directory) is required"
dl_target_init
umask 077; mkdir -p "$OUT/sql"; chmod 700 "$OUT"
mark() { echo "$(dl_ts) $STEP $*" >> "$OUT/times.txt"; }
need_pass() { [[ -f "$OUT/$1" ]] && grep -Eq "$2" "$OUT/$1" || dl_die "$1 has no $2 in $OUT (run that step first)"; }
need_approval() {
  [[ "$DL_TARGET" == local ]] && return 0
  [[ -n "${KODHANE_LIVE_APPROVAL:-}" ]] || dl_die "live $STEP needs KODHANE_LIVE_APPROVAL (who approved, when)"
  mark "approval: $KODHANE_LIVE_APPROVAL"
}
strip_tx() { python3 - "$1" <<'PY'
import sys
lines = open(sys.argv[1]).read().split('\n')
b = [i for i, l in enumerate(lines) if l == 'begin;']; c = [i for i, l in enumerate(lines) if l == 'commit;']
assert len(b) == 1 and len(c) == 1 and b[0] < c[0], 'expected exactly one top-level begin; / commit; in ' + sys.argv[1]
print('\n'.join(l if i not in (b[0], c[0]) else '-- (' + l + ' removed: runs inside the install transaction)' for i, l in enumerate(lines)))
PY
}
run() {  # run <name>
  local f="$OUT/sql/$1.sql" rc; [[ -r "$f" ]] || dl_die "missing $f (run build)"
  mark "$1 start ($(md5sum < "$f" | cut -c1-32))"; dl_run_sql "$f" "$OUT/$1.out"; rc=$?; mark "$1 end rc=$rc"; return $rc
}
case "$STEP" in
  build)
    ( cd "$SB" && md5sum --quiet -c "$D/inputs.md5" ) || dl_die "input files differ from kodhane_deletion_log/inputs.md5 (reviewed versions)"
    S="$OUT/sql"
    { echo "-- generated by kodhane_deletion_log_install.sh build: preflight (READ ONLY)"; echo "$DL_PREFIX"; echo "begin read only;"
      cat "$D/preflight.sql"; echo "commit;"; echo "select 'PREFLIGHT|PASS';"; } > "$S/preflight.sql"
    for k in dryrun install; do
      { echo "-- generated by kodhane_deletion_log_install.sh build: $k (migration 20261003040000 + install check, one transaction)"
        echo "$DL_PREFIX"; echo "begin;"; echo "set local lock_timeout = '5s';"; strip_tx "$SB/$MIG" || exit 1; cat "$D/install_verify.sql"
        if [[ $k == dryrun ]]; then echo "rollback;"; echo "select 'DRYRUN|PASS|rolled back';"; else echo "commit;"; echo "select 'INSTALL|PASS|committed';"; fi
      } > "$S/$k.sql" || dl_die "build failed"
    done
    { echo "-- generated by kodhane_deletion_log_install.sh build: verify (READ ONLY)"; echo "$DL_PREFIX"; echo "begin read only;"
      cat "$D/install_verify.sql"; echo "commit;"; echo "select 'VERIFY|PASS';"; } > "$S/verify.sql"
    for loss in no yes; do
      { echo "-- generated by kodhane_deletion_log_install.sh build: rollback"; echo "$DL_PREFIX"; echo "begin;"
        [[ $loss == yes ]] && echo "set local kodhane.deletion_log_allow_loss = on;   -- KODHANE_ALLOW_DELETION_LOG_LOSS=on: the list rows are dropped"
        strip_tx "$SB/$RB" || exit 1
        echo "select 'CHECK|rolled_back|' || (to_regclass('kodhane_private.deletion_log') is null and to_regnamespace('kodhane_private') is null);"
        echo "commit;"; echo "select 'ROLLBACK|PASS|committed';"; } > "$S/rollback$([[ $loss == yes ]] && echo _allow_loss).sql" || dl_die "build failed"
    done
    ( cd "$S" && md5sum preflight.sql dryrun.sql install.sql verify.sql rollback.sql rollback_allow_loss.sql > ../sql.md5 )
    { echo "BUILD|PASS"; ( cd "$SB" && md5sum $MIG $RB ); cat "$OUT/sql.md5"; } | tee "$OUT/build.out" ;;
  preflight)
    run preflight; rc=$?; grep -E '^INFO\|' "$OUT/preflight.out"; grep -oE '(STOP|ERROR): .*' "$OUT/preflight.out"
    [[ $rc == 0 ]] && grep -q '^PREFLIGHT|PASS' "$OUT/preflight.out" || dl_die "preflight did not pass (see $OUT/preflight.out)"
    echo "PREFLIGHT|PASS" ;;
  dryrun|install|verify)
    [[ $STEP == dryrun ]] && need_pass preflight.out '^PREFLIGHT\|PASS'
    if [[ $STEP == install ]]; then need_approval; need_pass preflight.out '^PREFLIGHT\|PASS'; need_pass dryrun.out '^DRYRUN\|PASS'; fi
    ( cd "$OUT/sql" && md5sum --quiet -c ../sql.md5 ) || dl_die "generated SQL changed since build"
    run $STEP; rc=$?; grep -E '^(CHECK|DLVERIFY)\|' "$OUT/$STEP.out"; grep -oE 'ERROR: .*' "$OUT/$STEP.out" | head -n3
    U=$(echo $STEP | tr a-z A-Z)
    [[ $rc == 0 ]] && grep -q "^$U|PASS" "$OUT/$STEP.out" || dl_die "$STEP did not pass (see $OUT/$STEP.out; nothing committed if the error came before COMMIT)"
    echo "$U|PASS" ;;
  rollback)
    need_approval; f=rollback; [[ "${KODHANE_ALLOW_DELETION_LOG_LOSS:-}" == on ]] && f=rollback_allow_loss
    ( cd "$OUT/sql" && md5sum --quiet -c ../sql.md5 ) || dl_die "generated SQL changed since build"
    run $f; rc=$?; grep -E '^CHECK\|' "$OUT/$f.out"; grep -oE 'ERROR: .*' "$OUT/$f.out" | head -n3
    [[ $rc == 0 ]] && grep -q '^ROLLBACK|PASS' "$OUT/$f.out" || dl_die "rollback did not commit (see $OUT/$f.out)"
    echo "ROLLBACK|PASS" ;;
  *) sed -n '2,18p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 2 ;;
esac
