#!/usr/bin/env python3
"""Check deletion log export files and build the reapply / verify SQL (ops/kodhane_deletion_log_reapply.sh).
usage: build_reapply.py <mode reapply|verify|dryrun> <delete.sql> <reapply.sql> <out.sql> <file.csv>...
Every file must: be named kodhane-deletion-log-YYYYMMDDTHHMMSSZ.csv, have <file>.md5 ("<md5>  <name>") that matches,
carry the exact header and only well-formed rows. Any bad file -> exit 1, nothing written."""
import hashlib, os, re, sys
mode, delete_sql, main_sql, out_sql, files = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5:]
HEADER = 'user_id,scope,deleted_at_utc,approval_ref'
NAME = re.compile(r'^kodhane-deletion-log-\d{8}T\d{6}Z\.csv$')
ROW = re.compile(r'^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}),(account|kodhane),'
                 r'(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}Z),((?:self|info|purge):[^@,"\\\x00-\x1f\x7f]{1,200})$')
bad, rows = [], []
if not files: bad.append('no export files')
for f in files:
    n = os.path.basename(f)
    if not NAME.match(n): bad.append('%s: unexpected file name' % n); continue
    try: data = open(f, 'rb').read()
    except OSError as e: bad.append('%s: %s' % (n, e)); continue
    try: m = open(f + '.md5').read().split()
    except OSError: bad.append('%s: no .md5 file' % n); continue
    if len(m) != 2 or m[1] != n or not re.match(r'^[0-9a-f]{32}$', m[0]): bad.append('%s: malformed .md5 file' % n); continue
    if hashlib.md5(data).hexdigest() != m[0]: bad.append('%s: md5 does not match (file changed or damaged)' % n); continue
    try: text = data.decode('utf-8')
    except UnicodeDecodeError: bad.append('%s: not UTF-8' % n); continue
    lines = text.split('\n')
    if lines and lines[-1] == '': lines.pop()
    else: bad.append('%s: no final newline (truncated?)' % n); continue
    if not lines or lines[0] != HEADER: bad.append('%s: header is not %s' % (n, HEADER)); continue
    for i, l in enumerate(lines[1:], 2):
        mm = ROW.match(l)
        if not mm: bad.append('%s line %d: malformed row' % (n, i)); break
        rows.append(mm.groups())
if bad:
    print('\n'.join('BAD|' + b for b in bad)); sys.exit(1)
src = open(delete_sql).read().split('\n')
b = [i for i, l in enumerate(src) if l == 'do $del$']; e = [i for i, l in enumerate(src) if l == 'end $del$;']
assert len(b) == 1 and len(e) == 1 and b[0] < e[0], 'DO block of the delete file not found'
body = '\n'.join(src[b[0] + 1:e[0] + 1])
whole = open(delete_sql).read()
cb = whole.index('  -- <kodhane_del_counts>'); ce = whole.index('  -- </kodhane_del_counts>') + len('  -- </kodhane_del_counts>')
counts = whole[cb:ce]
q = lambda s: "'" + s.replace("'", "''") + "'"
with open(out_sql, 'w') as o:
    o.write('-- generated by supabase/ops/kodhane_deletion_log_reapply.sh %s from %d file(s), %d row(s)\n' % (mode, len(files), len(rows)))
    o.write('\\set ON_ERROR_STOP on\n\\set QUIET on\n\\pset format unaligned\n\\pset tuples_only on\n\\pset footer off\n')
    o.write('begin;\nset local lock_timeout = \'5s\';\nset local statement_timeout = \'600s\';\n')
    o.write("select set_config('kodhane_dl.mode', %s, true) is null;\n" % q('verify' if mode == 'verify' else 'reapply'))
    o.write('create temp table dl_in (user_id uuid, scope text, deleted_at timestamptz, approval_ref text) on commit drop;\n')
    for i in range(0, len(rows), 200):
        o.write('insert into pg_temp.dl_in values\n' + ',\n'.join('(%s, %s, %s, %s)' % (q(u), q(s), q(t), q(r)) for u, s, t, r in rows[i:i + 200]) + ';\n')
    o.write('-- ======== pg_temp.kodhane_del_run(): DO block of ops/kodhane_account_delete.sql, verbatim\n')
    o.write('create or replace function pg_temp.kodhane_del_run() returns void language plpgsql as $del$\n' + body + '\n')
    o.write('-- ======== pg_temp.kodhane_dl_counts(uuid): <kodhane_del_counts> of ops/kodhane_account_delete.sql, verbatim\n')
    o.write('create or replace function pg_temp.kodhane_dl_counts(p_uid uuid) returns table (o_cat text, o_rel text, o_n bigint)\n'
            'language plpgsql as $cnt$\nbegin\n  perform set_config(\'kodhane_del.uid\', p_uid::text, true);\n'
            '  return query select x.cat, x.rel, x.n from (\n' + counts + '\n    ) x;\nend $cnt$;\n')
    o.write(open(main_sql).read())
    o.write('commit;\nselect \'REAPPLY|PASS|committed\';\n' if mode == 'reapply' else 'rollback;\nselect \'%s|END|rolled back\';\n' % mode.upper())
print('OK|files|%d|rows|%d' % (len(files), len(rows)))
